nginx:
  image: benhall/nginx-proxy:latest
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  ports:
    - 80:80
  environment:
    DEFAULT_HOST: 'my.container.com'
  restart: always
web:
  build: .
  links:
    - redis
  environment:
    VIRTUAL_HOST: 'my.container.com'
    NODE_ENV: 'production'
  restart: always
redis:
  image: redis:2.8.21
  ports:
    - 6379:6379
  restart: always
